baseURL: https://wh1tej0ker.github.io
languageCode: zh-CN
title: Wh1teJ0kerã®Blog
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
params:
  brand: HOME
  author: Wh1teJ0ker
  avatarURL: /joker.jpg
  authorDescription: ğŸ‘‹ æˆ‘æ˜¯ @Wh1teJ0ker ï½œä¸“æ³¨ CTFï¼ˆWeb & Miscï¼‰ï½œçƒ­çˆ± AI ä¸å®‰å…¨
  info: æ¬¢è¿æ¥åˆ°æˆ‘çš„åšå®¢
  favicon: /favicon.ico
  comments:
    giscus:
      enable: true
      repo: Wh1teJ0ker/wh1tej0ker.github.io
      repo_id: R_kgDOMbVXlA
      category: Announcements
      category_id: DIC_kwDOMbVXlM4CovNt
      mapping: pathname
      position: top
      lang: zh
  analytics:
    umami:
      enable: true
      website_id: 8ab9bf68-dca3-4807-a3b3-8ef0b17ec8c5
      url: https://analytics.umami.is/script.js
menu:
  main:
    - identifier: categories
      name: åˆ†ç±»
      url: /categories/
      weight: 2
    - identifier: archives
      name: å½’æ¡£
      url: /archives/
      weight: 3
    - identifier: friends
      name: å‹é“¾
      url: /friends/
      weight: 4
    - identifier: about
      name: å…³äº
      url: /about/
      weight: 5
markup:
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: solarized-light
